"""Synthetic occlusion utilities for the TLS stem-detection pipeline.

Author: Shahab Alaedin Baloochi
"""

from .synthetic_occlusion import (
    EPS,
    EVALUATION_BAND_COUNT,
    TRAINING_BAND_PROBABILITY,
    AXIS_PROXIMAL_PROBABILITY,
    OFF_AXIS_CROWN_PROBABILITY,
    UNCONSTRAINED_PROBABILITY,
    AXIS_PROXIMAL_MAX_RADIAL_FRACTION,
    OFF_AXIS_CROWN_MIN_RADIAL_FRACTION,
    OFF_AXIS_CROWN_MIN_Z_NORM,
    Range,
    AngleRange,
    OcclusionGeometryConfig,
    TreeOcclusionFrame,
    OcclusionRegion,
    OcclusionScenario,
    OcclusionApplication,
    build_tree_frame,
    valid_k_values,
    validate_k_for_height,
    sample_placement_classes,
    generate_scenario,
    generate_two_training_variants,
    validate_scenario,
    apply_scenario,
    remove_occluded_points,
    paper_protocol_summary,
)

__all__ = [
    "EPS",
    "EVALUATION_BAND_COUNT",
    "TRAINING_BAND_PROBABILITY",
    "AXIS_PROXIMAL_PROBABILITY",
    "OFF_AXIS_CROWN_PROBABILITY",
    "UNCONSTRAINED_PROBABILITY",
    "AXIS_PROXIMAL_MAX_RADIAL_FRACTION",
    "OFF_AXIS_CROWN_MIN_RADIAL_FRACTION",
    "OFF_AXIS_CROWN_MIN_Z_NORM",
    "Range",
    "AngleRange",
    "OcclusionGeometryConfig",
    "TreeOcclusionFrame",
    "OcclusionRegion",
    "OcclusionScenario",
    "OcclusionApplication",
    "build_tree_frame",
    "valid_k_values",
    "validate_k_for_height",
    "sample_placement_classes",
    "generate_scenario",
    "generate_two_training_variants",
    "validate_scenario",
    "apply_scenario",
    "remove_occluded_points",
    "paper_protocol_summary",
]